name: Vps-push code
on: 
  push:
    branches:
      - 'main'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: npm install
      - run: npm start
  pushCode:
    runs-on: ubuntu-latest
    steps:
      - uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSHRSA }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
      - run: ssh-keyscan -H ${{secrets.ip}} >> ~/.ssh/known_hosts
      - run: ssh ${{secrets.username}}@${{secrets.ip}} "cd ${{ secrets.path }} && git checkout ${{ secrets.branch }} && git reset --hard HEAD && npm clean install"
      - run: ssh ${{secrets.username}}@${{secrets.ip}} "pm2 restart ${{ secrets.pm2ID }}"

